# Generated by Django 6.0.3 on 2026-03-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shveya', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parties',
            new_name='Party',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('quantity_line', models.IntegerField()),
                ('tshirt_count', models.IntegerField()),
                ('four_x', models.CharField(max_length=50)),
                ('four_x_count', models.IntegerField()),
                ('raspash', models.CharField(max_length=50)),
                ('raspash_count', models.IntegerField()),
                ('beika', models.CharField(max_length=50)),
                ('beika_count', models.IntegerField()),
                ('strochka', models.CharField(max_length=50)),
                ('strochka_count', models.IntegerField()),
                ('gorlo', models.CharField(max_length=50)),
                ('gorlo_count', models.IntegerField()),
                ('ytyg', models.CharField(max_length=50)),
                ('ytyg_count', models.IntegerField()),
                ('otk', models.CharField(max_length=50)),
                ('otk_count', models.IntegerField()),
                ('ypakovka', models.CharField(max_length=50)),
                ('ypakovka_count', models.IntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='shveya.party')),
            ],
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
