# Generated by Django 6.0.3 on 2026-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shveya', '0002_rename_parties_party_material_delete_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='beika',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='beika_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='four_x',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='four_x_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='gorlo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='gorlo_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='otk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='otk_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='raspash',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='raspash_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='strochka',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='strochka_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='ypakovka',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='ypakovka_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='ytyg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='ytyg_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
