# Generated by Django 6.0.3 on 2026-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shveya', '0004_alter_material_beika_alter_material_four_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='beika',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='four_x',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='gorlo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='otk',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='raspash',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='strochka',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='ypakovka',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='ytyg',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
